language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.8"

install:
    - dzil authordeps --missing | cpanm --no-skip-satisfied
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied

script:
    - dzil test --author --release

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24a03a09e19da7dea2d9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always