dist: trusty
language: perl

perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.10"

install:
    - dzil authordeps --missing | cpanm --no-skip-satisfied --notest
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied --notest

script:
    - dzil test --author --release

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24a03a09e19da7dea2d9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
